In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
d = {'first Score':[100, 90, np.nan, 95],
        'second Score':[30, 45, 56, np.nan],
        'third Score':[np.nan, 40, 80, 98]}
df=pd.DataFrame(d)
mv=df.isnull()
print(mv)

   first Score  second Score  third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [5]:
data={'Name':['Amit', 'Sita', np.nan, 'Raj'],
        'Age':[25, np.nan, 22, 28]}

df=pd.DataFrame(data)
print(df.isna())

    Name    Age
0  False  False
1  False   True
2   True  False
3  False  False

In [6]:
d = {'first Score': [100, 90, np.nan, 95],
     'second Score': [30, 45, 56, np.nan],
     'third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)
mv = df.notnull()
print(mv)

   first Score  second Score  third Score
0         True          True        False
1         True          True         True
2        False          True         True
3         True         False         True

In [7]:
d = {'sirst Score': [100, 90, np.nan, 95],
    'second Score': [30, 45, 56, np.nan],
    'third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)
df.fillna(0)

   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [9]:
df.ffill()

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2         90.0          56.0         80.0
3         95.0          56.0         98.0

In [10]:
df.bfill()

   First Score  Second Score  Third Score
0        100.0          30.0         40.0
1         90.0          45.0         40.0
2         95.0          56.0         80.0
3         95.0           NaN         98.0

In [13]:
data = {'Score': [10, np.nan, 30, np.nan, 50]}
df = pd.DataFrame(data)
df['Score'] = df['Score'].interpolate()
print(df)

   Score
0   10.0
1   20.0
2   30.0
3   40.0
4   50.0

In [14]:
df = pd.DataFrame({"A": [12, 4, 5, None, 1], 
                   "B": [None, 2, 54, 3, None], 
                   "C": [20, 16, None, 3, 8], 
                   "D": [14, 3, None, None, 6]})  
k=df.interpolate(method ='linear', limit_direction ='forward')
print(df)
print(k)

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   NaN   NaN
3   NaN   3.0   3.0   NaN
4   1.0   NaN   8.0   6.0
      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   9.5   4.0
3   3.0   3.0   3.0   5.0
4   1.0   3.0   8.0   6.0

In [15]:
dict = {'first Score': [100, 90, np.nan, 95],
        'second Score': [30, np.nan, 45, 56],
        'third Score': [52, 40, 80, 98],
        'fourth Score': [np.nan, np.nan, np.nan, 65]}
df = pd.DataFrame(dict)
print(df)
df.dropna()

   first Score  second Score  third Score  fourth Score
0        100.0          30.0           52           NaN
1         90.0           NaN           40           NaN
2          NaN          45.0           80           NaN
3         95.0          56.0           98          65.0

   first Score  second Score  third Score  fourth Score
3         95.0          56.0           98          65.0

In [17]:
dict = {'first Score': [100, np.nan, np.nan, 95],
        'second Score': [30, np.nan, 45, 56],
        'third Score': [52, np.nan, 80, 98],
        'fourth Score': [np.nan, np.nan, np.nan, 65]}
df = pd.DataFrame(dict)
print(df)
df.dropna(how='all')

   first Score  second Score  third Score  fourth Score
0        100.0          30.0         52.0           NaN
1          NaN           NaN          NaN           NaN
2          NaN          45.0         80.0           NaN
3         95.0          56.0         98.0          65.0

   first Score  second Score  third Score  fourth Score
0        100.0          30.0         52.0           NaN
2          NaN          45.0         80.0           NaN
3         95.0          56.0         98.0          65.0

In [ ]:
dict = {'first Score': [100, np.nan, np.nan, 95],
        'second Score': [30, np.nan, np.nan, 56],
        'third Score': [52, np.nan, 80, 98],
        'fourth Score': [60, 67, 68, 65]}
df = pd.DataFrame(dict)
print(df)
df.dropna(axis=0)   
df.dropna(axis=0)