In [2]:
import pandas as pd

In [4]:
data={"Name": ["Alice", "Bob", "Alice", "David"],
        "Age": [25, 30, 25, 40],
        "City": ["NY", "LA", "NY", "Chicago"]}

df=pd.DataFrame(data)
print(df)
print('--------------------------------------------------------------------------------------------------------------------------')
df_cl=df.drop_duplicates()
print(df_cl)

    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
2  Alice   25       NY
3  David   40  Chicago
--------------------------------------------------------------------------------------------------------------------------
    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
3  David   40  Chicago

In [5]:
df=pd.DataFrame({'Name': ['Alice', 'Bob', 'Alice', 'David'],
                  'Age': [25, 30, 25, 40],
                  'City': ['NY', 'LA', 'SF', 'Chicago']})
df_cl=df.drop_duplicates(subset=["Name"])
print(df_cl)

    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
3  David   40  Chicago

In [10]:
df = pd.DataFrame({   'Name': ['Alice', 'Bob', 'Alice', 'David'],
                'Age': [25, 30, 25, 40],
                'City': ['NY', 'LA', 'NY', 'Chicago']})
df_cl= df.drop_duplicates(keep='last')
print(df_cl)

    Name  Age     City
1    Bob   30       LA
2  Alice   25       NY
3  David   40  Chicago

In [13]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Alice', 'David'],
                    'Age': [25, 30, 25, 40],
                    'City': ['NY', 'LA', 'NY', 'Chicago']})
df_cl=df.drop_duplicates(keep=False)
print(df_cl)

    Name  Age     City
1    Bob   30       LA
3  David   40  Chicago

In [14]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Alice', 'David'],
                 'Age': [25, 30, 25, 40],
                 'City': ['NY', 'LA', 'NY', 'Chicago']})
df.drop_duplicates(inplace=True)
print(df)

    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
3  David   40  Chicago

In [15]:
import pandas as pd

data = {"Name": ["Alice", "Bob", "Alice", "David", "Bob"],
        "Age": [25, 20, 25, 40, 30],
        "City": ["NY", "LA", "NY", "Chicago", "LA"]}
df=pd.DataFrame(data)
df_cleaned=df.drop_duplicates(subset=["Name", "City"])
print(df)
print(df_cleaned)

    Name  Age     City
0  Alice   25       NY
1    Bob   20       LA
2  Alice   25       NY
3  David   40  Chicago
4    Bob   30       LA
    Name  Age     City
0  Alice   25       NY
1    Bob   20       LA
3  David   40  Chicago

In [16]:
data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'], 
        'Age': [25, 30, 22, 35, 28], 
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'], 
        'Salary': [50000, 55000, 40000, 70000, 48000]}
df=pd.DataFrame(data)
print(df.dtypes)
df['Age']=df['Age'].astype(float)
print(df.dtypes)

Name        str
Age       int64
Gender      str
Salary    int64
dtype: object
Name          str
Age       float64
Gender        str
Salary      int64
dtype: object

In [18]:
import numpy as np
df = pd.DataFrame({"FirstName": ['Vipul', 'Ashish', 'Milan'],
                    "Gender": ["", "", ""],
                    "Age": [0, 0, 0]})
df['Department'] = np.nan    
print(df)

  FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

In [22]:
df = pd.DataFrame({"FirstName":['Vipul', 'Ashish', 'Milan'],
                    "Gender":["", "", ""],
                    "Age":[0, 0, 0]})
df['Department'] = np.nan
display(df)
df.dropna(how='all',axis=1,inplace=True)
display(df)

  FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

  FirstName Gender  Age
0     Vipul           0
1    Ashish           0
2     Milan           0

In [23]:
df = pd.DataFrame({'FirstName': ['Vipul', 'Ashish', 'Milan'],
                    "Gender": ["", "", ""],
                    "Age": [0, 0, 0]})
df['Department'] = np.nan
display(df)
nan_value=float("NaN")
k = df.replace("", nan_value)
display(k)
k.dropna(how='all',axis=1,inplace=True)
display(k)

  FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

  FirstName Gender  Age  Department
0     Vipul    NaN    0         NaN
1    Ashish    NaN    0         NaN
2     Milan    NaN    0         NaN

  FirstName  Age
0     Vipul    0
1    Ashish    0
2     Milan    0

In [24]:
df = pd.DataFrame({"FirstName": ['Vipul', 'Ashish', 'Milan'],
                            "Gender": ["", "", ""],
                            "Age": [0, 0, 0]})
df['Department'] = np.nan
display(df)
nan_value=float("NaN")
df.replace(0, nan_value, inplace=True)
df.dropna(how='all', axis=1, inplace=True)
display(df)

  FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

  FirstName Gender
0     Vipul
1    Ashish
2     Milan

In [25]:
data = {'Names': ['Gulshan', 'Shashank', 'Bablu', 'Abhishek', 'Anand', np.nan, 'Pratap'],
        'City': ['Delhi', 'Mumbai', 'Kolkata', 'Delhi', 'Chennai', 'Bangalore', 'Hyderabad']}
df = pd.DataFrame(data)
print(df)
print(df['City'].str.get_dummies())

      Names       City
0   Gulshan      Delhi
1  Shashank     Mumbai
2     Bablu    Kolkata
3  Abhishek      Delhi
4     Anand    Chennai
5       NaN  Bangalore
6    Pratap  Hyderabad
   Bangalore  Chennai  Delhi  Hyderabad  Kolkata  Mumbai
0          0        0      1          0        0       0
1          0        0      0          0        0       1
2          0        0      0          0        1       0
3          0        0      1          0        0       0
4          0        1      0          0        0       0
5          1        0      0          0        0       0
6          0        0      0          1        0       0

In [26]:
data_frame = pd.DataFrame([['tom', 10],['nick', '15'],['juli', 14.5]],columns=['Name', 'Age'])
print(data_frame.info())
for column in data_frame.columns:
    print(column,':',pd.api.types.infer_dtype(data_frame[column]))

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      object
dtypes: object(1), str(1)
memory usage: 180.0+ bytes
None
Name : string
Age : mixed-integer

In [28]:
data_frame = pd.DataFrame( [['tom', 10], ['nick', '15'], ['juli', 14.8]], columns=['Name', 'Age'])
data_frame[column]=data_frame[column].astype(int)
for column in data_frame.columns:
    print(column,':',pd.api.types.infer_dtype(data_frame[column]))

Name : string
Age : integer