In [1]:
import pandas as pd

In [2]:
df=pd.read_excel("employee.xlsx")

In [6]:
print(df.head())

   EmpID           Name  Gender  Age Department   Salary JoiningDate  \
0    101     John Smith    Male   28         IT  55000.0  2022-01-15
1    102  Sarah Johnson  Female   31         HR  48000.0  2021-05-22
2    103  Michael Brown    Male  NaN    Finance  62000.0  2020-11-10
3    104    Emily Davis  Female   29         IT  58000.0  2023-03-15
4    105   David Wilson    Male   45      Sales      NaN  2019-07-18

          City  PerformanceScore
0     New York               8.0
1      Chicago               7.0
2      Houston               9.0
3  Los Angeles               8.0
4      Phoenix               6.0

In [41]:
df.tail()

,EmpID,Name,Gender,Age,Department,Salary,JoiningDate,City,PerformanceScore
20,121,John Smith,Male,28,IT,55000.0,2022-01-15,New York,8.0
21,122,Sophia Green,Female,29,HR,53000.0,2022-09-09,Chicago,7.0
22,123,Lucas Adams,male,32,finance,61000.0,2021-08-18,New York,8.0
23,124,Isabella Baker,FEMALE,26,IT,59000.0,2023-04-11,Houston,9.0
24,125,William Carter,Male,150,Sales,50000.0,2020-05-19,Phoenix,5.0

In [9]:
df.shape

(25, 9)

In [42]:
df.columns

Index(['EmpID', 'Name', 'Gender', 'Age', 'Department', 'Salary', 'JoiningDate',
       'City', 'PerformanceScore'],
      dtype='str')

In [43]:
df.dtypes

EmpID                        int64
Name                           str
Gender                         str
Age                         object
Department                     str
Salary                     float64
JoiningDate         datetime64[us]
City                           str
PerformanceScore           float64
dtype: object

In [27]:
print(df.isnull())

    EmpID   Name  Gender    Age  Department  Salary  JoiningDate   City  \
0   False  False   False  False       False   False        False  False
1   False  False   False  False       False   False        False  False
2   False  False   False   True       False   False        False  False
3   False  False   False  False       False   False        False  False
4   False  False   False  False       False    True        False  False
5   False  False   False  False       False   False        False  False
6   False  False   False  False       False   False        False  False
7   False  False   False  False       False   False        False  False
8   False  False   False  False       False   False        False  False
9   False  False   False  False       False   False        False  False
10  False  False   False  False       False   False        False  False
11  False  False   False  False       False   False        False  False
12  False  False   False  False       False   False        False  False
13  False  False   False  False       False   False        False  False
14  False  False   False  False       False   False        False  False
15  False  False   False  False       False   False         True  False
16  False  False   False  False       False   False        False  False
17  False  False   False  False       False   False        False  False
18  False  False   False   True       False   False        False  False
19  False  False   False  False       False   False        False  False
20  False  False   False  False       False   False        False  False
21  False  False   False  False       False   False        False  False
22  False  False   False  False       False   False        False  False
23  False  False   False  False       False   False        False  False
24  False  False   False  False       False   False        False  False

    PerformanceScore
0              False
1              False
2              False
3              False
4              False
5               True
6              False
7              False
8              False
9              False
10             False
11             False
12             False
13             False
14             False
15             False
16             False
17             False
18             False
19             False
20             False
21             False
22             False
23             False
24             False

In [23]:
print(df["Name"])

0          John Smith
1       Sarah Johnson
2       Michael Brown
3         Emily Davis
4        David Wilson
5      Jessica Taylor
6      Chris Anderson
7       Amanda Thomas
8        Daniel Moore
9       Olivia Martin
10        James White
11      Sophia Harris
12       Robert Clark
13         Emma Lewis
14        Liam Walker
15           Ava Hall
16         Noah Allen
17          Mia Young
18         Ethan King
19    Charlotte Scott
20         John Smith
21       Sophia Green
22        Lucas Adams
23     Isabella Baker
24     William Carter
Name: Name, dtype: str

In [28]:
df[["Name","Salary"]]

               Name   Salary
0        John Smith  55000.0
1     Sarah Johnson  48000.0
2     Michael Brown  62000.0
3       Emily Davis  58000.0
4      David Wilson      NaN
5    Jessica Taylor  51000.0
6    Chris Anderson  67000.0
7     Amanda Thomas  47000.0
8      Daniel Moore  56000.0
9     Olivia Martin  49000.0
10      James White  72000.0
11    Sophia Harris  65000.0
12     Robert Clark  -5000.0
13       Emma Lewis  51000.0
14      Liam Walker  45000.0
15         Ava Hall  68000.0
16       Noah Allen  61000.0
17        Mia Young  57000.0
18       Ethan King  52000.0
19  Charlotte Scott  64000.0
20       John Smith  55000.0
21     Sophia Green  53000.0
22      Lucas Adams  61000.0
23   Isabella Baker  59000.0
24   William Carter  50000.0

In [47]:
df.isnull().any(axis=1)

0     False
1     False
2      True
3     False
4      True
5      True
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16    False
17    False
18     True
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool

In [45]:
df.isnull().sum()

EmpID               0
Name                0
Gender              0
Age                 2
Department          0
Salary              1
JoiningDate         1
City                0
PerformanceScore    1
dtype: int64

In [66]:
df.dtypes

EmpID                        int64
Name                           str
Gender                         str
Age                         object
Department                     str
Salary                     float64
JoiningDate         datetime64[us]
City                           str
PerformanceScore           float64
dtype: object

In [75]:
print(df['Age'].dtypes)

object

In [82]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df['Age']

0      28
1      31
2      36
3      29
4      45
5      27
6      34
7      36
8      30
9      26
10     41
11     33
12     38
13     29
14     27
15     31
16     35
17     28
18     36
19     30
20     28
21     29
22     32
23     26
24    150
Name: Age, dtype: int64

In [84]:
df["Salary"]= df["Salary"].fillna(df["Salary"].median())
df["Salary"]

0     55000.0
1     48000.0
2     62000.0
3     58000.0
4     55500.0
5     51000.0
6     67000.0
7     47000.0
8     56000.0
9     49000.0
10    72000.0
11    65000.0
12    -5000.0
13    51000.0
14    45000.0
15    68000.0
16    61000.0
17    57000.0
18    52000.0
19    64000.0
20    55000.0
21    53000.0
22    61000.0
23    59000.0
24    50000.0
Name: Salary, dtype: float64

In [90]:
print("orginaldata")
print(df)
cleandata=df.drop_duplicates(inplace=True)
print("cleandata")
print(cleandata)

orginaldata
    EmpID             Name  Gender  Age Department   Salary JoiningDate  \
0     101       John Smith    Male   28         IT  55000.0  2022-01-15
1     102    Sarah Johnson  Female   31         HR  48000.0  2021-05-22
2     103    Michael Brown    Male   36    Finance  62000.0  2020-11-10
3     104      Emily Davis  Female   29         IT  58000.0  2023-03-15
4     105     David Wilson    Male   45      Sales  55500.0  2019-07-18
5     106   Jessica Taylor  Female   27  Marketing  51000.0  2022-08-30
6     107   Chris Anderson    Male   34    Finance  67000.0  2020-12-15
7     108    Amanda Thomas  Female   36         HR  47000.0  2021-02-11
8     109     Daniel Moore    Male   30         IT  56000.0  2022-06-05
9     110    Olivia Martin  Female   26      Sales  49000.0  2023-01-12
10    111      James White    Male   41  Marketing  72000.0  2018-09-21
11    112    Sophia Harris  Female   33    Finance  65000.0  2020-04-15
12    113     Robert Clark    Male   38         IT  -5000.0  2019-11-05
13    114       Emma Lewis  Female   29      Sales  51000.0  2022-05-16
14    115      Liam Walker    Male   27         HR  45000.0  2023-02-20
15    116         Ava Hall  Female   31    Finance  68000.0         NaT
16    117       Noah Allen    Male   35  Marketing  61000.0  2021-10-18
17    118        Mia Young  Female   28         IT  57000.0  2022-03-09
18    119       Ethan King    Male   36      Sales  52000.0  2020-07-14
19    120  Charlotte Scott  Female   30    Finance  64000.0  2021-12-01
20    121       John Smith    Male   28         IT  55000.0  2022-01-15
21    122     Sophia Green  Female   29        HR   53000.0  2022-09-09
22    123      Lucas Adams    male   32    finance  61000.0  2021-08-18
23    124   Isabella Baker  FEMALE   26         IT  59000.0  2023-04-11
24    125   William Carter    Male  150      Sales  50000.0  2020-05-19

           City  PerformanceScore
0      New York               8.0
1       Chicago               7.0
2       Houston               9.0
3   Los Angeles               8.0
4       Phoenix               6.0
5       Chicago               NaN
6      New York               9.0
7       Houston               7.0
8   Los Angeles               8.0
9       Phoenix               5.0
10      Chicago               9.0
11     New York               8.0
12      Houston               7.0
13  Los Angeles               6.0
14      Phoenix               8.0
15      Chicago               9.0
16     New York               7.0
17      Houston               8.0
18  Los Angeles               6.0
19      Phoenix               9.0
20     New York               8.0
21      Chicago               7.0
22     New York               8.0
23      Houston               9.0
24      Phoenix               5.0
cleandata
None

In [92]:
df["Department"] = df["Department"].str.strip()
df["Department"]

0            IT
1            HR
2       Finance
3            IT
4         Sales
5     Marketing
6       Finance
7            HR
8            IT
9         Sales
10    Marketing
11      Finance
12           IT
13        Sales
14           HR
15      Finance
16    Marketing
17           IT
18        Sales
19      Finance
20           IT
21           HR
22      finance
23           IT
24        Sales
Name: Department, dtype: str

In [94]:
df["Gender"] = df["Gender"].str.upper()
df["Gender"]

0       MALE
1     FEMALE
2       MALE
3     FEMALE
4       MALE
5     FEMALE
6       MALE
7     FEMALE
8       MALE
9     FEMALE
10      MALE
11    FEMALE
12      MALE
13    FEMALE
14      MALE
15    FEMALE
16      MALE
17    FEMALE
18      MALE
19    FEMALE
20      MALE
21    FEMALE
22      MALE
23    FEMALE
24      MALE
Name: Gender, dtype: str

In [95]:
df["JoiningDate"] = pd.to_datetime(df["JoiningDate"])
df["JoiningDate"].dtypes

dtype('<M8[us]')

In [98]:
import numpy as np
df["Salary"] = np.where(df["Salary"] < 0, np.nan, df["Salary"])
df["Salary"]

0     55000.0
1     48000.0
2     62000.0
3     58000.0
4     55500.0
5     51000.0
6     67000.0
7     47000.0
8     56000.0
9     49000.0
10    72000.0
11    65000.0
12        NaN
13    51000.0
14    45000.0
15    68000.0
16    61000.0
17    57000.0
18    52000.0
19    64000.0
20    55000.0
21    53000.0
22    61000.0
23    59000.0
24    50000.0
Name: Salary, dtype: float64

In [99]:
df.to_csv("employees_cleaned.csv", index=False)